version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: your_db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
